### ISSUE TITLE
Crashing in free play

### ISSUE THREAD

**Issue by ShadowMercury6** [ClassicBoost/Psych-Forever-Definitive#1]
### Describe your bug here.

Hovering over a song with no ogg file, crashes it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ClassicBoost** [comment]
yeah I haven't added in a failsafe or anything if there is a missing ogg data (yet), probably better off adding a placeholder Inst file in the folder to prevent crashes.

**Comment by ClassicBoost** [comment]
should probably keep it how it's suppose to work
