### ISSUE TITLE
Null Object Reference??

### ISSUE THREAD

**Issue by ThePistolGod** [ClassicBoost/Psych-Forever-Definitive#2]
### Describe your bug here.

For some reason every time I tried to add in stuff its keeps saying "Null Object Reference error" I don't know what this means but its keeping me from adding in Lua scripts :(

Full error message:

And then Psych Forever crashed!
PlayState.hx (line 2718)
PlayState.hx (line 2546)
PlayState.hx (line 1179)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ClassicBoost/Psych-Forever-Definitive

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes I tried to add a background to Psych Forever

**Comment by ClassicBoost** [comment]
What code did you add when you added the stage?

**Comment by ThePistolGod** [comment]
> What code did you add when you added the stage?

well I didn't add any code to it. It just when i downloaded a mod it says "error Null object reference" and then crashes so i deleted the said mod and now every time i try to add in a sprite its says "error uncaught error: Null object reference" so I don't know what i did :/

**Comment by ClassicBoost** [comment]
Oh, okay so if you're adding a mod from psych engine, put everything in the data folder into the songs folder since the data folder doesn't exist. All charts go inside the songs folder

**Comment by ThePistolGod** [comment]
oh ok i'll try it hold on

**Comment by ThePistolGod** [comment]
ok its works for now so if I find anything else I will let you know thanks for helping :)
