### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by ytggobs** [ClassicBoost/Psych-Forever-Definitive#9]
### What feature do you want to get added on the **base** engine?

Add my translation in the base game and maybe add translation for the settings?
[french.json](https://github.com/ClassicBoost/Psych-Forever/files/15210164/french.json)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, Week 7, 6K+ support.

**Comment by ClassicBoost** [comment]
added
